# Generated by Django 3.2.9 on 2023-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_moment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='内容'),
        ),
    ]
