# Generated by Django 3.2.9 on 2023-06-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_moment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='content',
        ),
    ]
