# Generated by Django 3.2.9 on 2023-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_moment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='content',
            field=models.CharField(default='无内容', max_length=10000, verbose_name='内容'),
        ),
    ]
