# Generated by Django 3.2.9 on 2023-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_moment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_tourist',
            field=models.BooleanField(default=True, verbose_name='是否是游客'),
        ),
    ]
