# Generated by Django 3.2.9 on 2023-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_user_if_tourist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(default='pic/1.png', upload_to='pic/', verbose_name='头像'),
        ),
    ]
