# Generated by Django 3.2.9 on 2023-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=30, verbose_name='真实姓名')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('phone_number', models.CharField(max_length=100, verbose_name='手机号')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('content', models.CharField(default='无内容', max_length=10000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '联系信息表',
                'verbose_name_plural': '联系信息表',
                'db_table': 'Contact',
            },
        ),
    ]
