# Generated by Django 3.2.9 on 2023-06-17 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_moment_dianzan_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('moment_id', models.IntegerField(default=0, verbose_name='所属帖子')),
                ('content', models.CharField(default='无评论', max_length=10000, verbose_name='评论内容')),
                ('author_name', models.CharField(max_length=30, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '评论库',
                'verbose_name_plural': '评论库',
                'db_table': 'Comment',
            },
        ),
    ]
