# Generated by Django 3.2.19 on 2023-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=30, verbose_name='视频名称')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='视频路径')),
            ],
            options={
                'verbose_name': '视频库',
                'verbose_name_plural': '视频库',
                'db_table': 'Video',
            },
        ),
    ]
